services:
  vilms-gateway:
    image: docker-registry.viais.vision/vilms/vilms-gateway:latest
    container_name: vilms-gateway
    pull_policy: never
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./app:/workspace/app
      - ./assets/models/hf:/root/.cache/huggingface
    ports:
      - 8989:8000
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health_check"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - vilms-network

  vilms-ollama:
    image: ollama/ollama:latest
    container_name: vilms-ollama
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./assets/models/ollama:/root/.ollama
      - ./assets/models/hf:/models/hf
      - ./assets/models/gguf:/models/gguf
    command: serve
    networks:
      - vilms-network

networks:
  vilms-network:
    name: qvision
    external: true
